### ISSUE TITLE
 Develop A Responsive Resign For The Home Page.

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/search-by-time-github#12]
### Explanation:
 The project currently looks good on desktop, but on mobile still needs to be worked.

### Screenshots
Currently it looks:
![imagen](https://user-images.githubusercontent.com/66505715/157733191-255889c0-0d63-4e8d-8b02-cf8c9c9a6edb.png)

And in mobile looks:
![imagen](https://user-images.githubusercontent.com/66505715/157733723-03b2e06f-a593-44e4-aa9d-005f65806211.png)

It should look:
![imagen](https://user-images.githubusercontent.com/66505715/157733784-086a7254-3c0d-4667-9d23-615cfc974645.png)

### Checklist
 This issue can be closed when the following tasks are completed:
 
 - [ ] The page in mobile size looks like layout.
 - [ ] Azordev logo is at left-bottom corner of the page.
 - [ ] The size of the elements is slightly smaller than the size of the desktop.

### References:
- https://www.figma.com/file/Pw5EfnvCLnXox2mFS40kdW/Azordev?node-id=0%3A1

**Comment by carlosluis911207** [comment]
I want to be assigned to this task
