### ISSUE TITLE
Margins And Page Styles  /  Márgenes Y Estilos De Página

### ISSUE THREAD

**Issue by angelik0828** [Azordev/search-by-time-github#15]
## Explanation:
Make changes at a visual level, about the size that the language box, language icon, form container and form should have, size of the Azordev logo, and place a blue line in the footer. make the change in the next view too, take into account figma design with the distribution of spaces.

## Screenshots:
![vista_escritorio2](https://user-images.githubusercontent.com/4030477/158230392-553cd110-dcab-4907-badc-db0e993cbee4.png)
![vista_escritorio 6](https://user-images.githubusercontent.com/4030477/158230546-1479de15-b399-4c6e-8cab-ed8ef7616a8f.png)

## Checklist:

 - [ ] Change the size of the language box.
 - [ ] Language icon size.
 - [ ] Fix form container size.
 - [ ] Adapt form size.
 - [ ] Resize Azordev logo.
 - [ ] Put line in footer.
 
## References:
Be guided by the screen and by the design in Figma. https://www.figma.com/file/9hPU5c4waRbBOd8msfEnKa/Search_by_time_github?node-id=0%3A1
#### Related issues:
[ A list of related issues or issues that are dependencies of this issue.](https://github.com/Azordev/search-by-time-github/issues/12#issue-1165643854)

----

# Spanish Version:

## Explicación:
Hacer cambios a nivel visual, el tamaño que debe tener la caja de idioma, ícono de idioma, contenedor de formulario y formulario, también el tamaño del logo de Azordev. Colocar una línea azul en el pie de página, hacer el cambio en la siguiente vista y tomar en cuenta el diseño Figma con la distribución de espacios.

## Capturas de pantalla:
![desktop_view2](https://user-images.githubusercontent.com/4030477/158230392-553cd110-dcab-4907-badc-db0e993cbee4.png)
![vista escritorio 6](https://user-images.githubusercontent.com/4030477/158230546-1479de15-b399-4c6e-8cab-ed8ef7616a8f.png)

## Lista de Verificación:

 - [ ] Cambiar el tamaño del cuadro de idioma.
 - [ ] Tamaño del ícono de idioma.
 - [] Fijar el tamaño del contenedor de formulario.
 - [ ] Adaptar tamaño del formulario.
 - [ ] Cambiar el tamaño del logo de Azordev.
 - [ ] Poner línea en el pie de página.
 
## Referencias:
Déjate guiar por la pantalla y por el diseño en figma. https://www.figma.com/file/9hPU5c4waRbBOd8msfEnKa/Search_by_time_github?node-id=0%3A1
#### Asuntos relacionados:
[ Una lista de problemas relacionados o problemas que son dependencias de este problema.](https://github.com/Azordev/search-by-time-github/issues/12#issue-1165643854)

**Comment by Israel-Laguan** [comment]
What "Put line in footer." means? Like, add a `<hr>`?

**Comment by Eghinner** [comment]
Seems that figma design dont have this layout

**Comment by angelik0828** [comment]
@ildebr the links are updated, this change will be made or we can assign someone.

**Comment by angelik0828** [comment]
![image](https://user-images.githubusercontent.com/4030477/174303399-3688b2be-8491-438f-b728-23a941c835dc.png)

**Comment by hector-trompis** [comment]
This task is already passed to administration but I do not have access to be able to close it. Who collaborates with me and closes it or gives me the permissions? Thank you.

**Comment by hector-trompis** [comment]
This task has already been reported to the administration but it has not yet been closed, it does not let me close it. Can you give me the authorization to do it? Who can help me please? Thanks.
