### ISSUE TITLE
           The Border Of The Error Fields Is Too Thick

### ISSUE THREAD

**Issue by angelik0828** [Azordev/search-by-time-github#17]
The color used in the borders of the text fields is very thick and of a different tone, it is necessary to include the alert icon that is in the design.
The size of the text used in the alerts is also very large, check the fonts.

![Screenshot 2022-03-22 074615](https://user-images.githubusercontent.com/4030477/159485153-1d903070-4c7b-4424-871a-456718c85965.jpg)
![image](https://user-images.githubusercontent.com/4030477/159485235-fbfeb2e5-9bd8-4a76-993c-9ec33f007dc2.png)

#Reference 

https://www.figma.com/file/Pw5EfnvCLnXox2mFS40kdW/Azordev?node-id=0%3A1

_Originally posted by @angelik0828 in https://github.com/Azordev/search-by-time-github/issues/16#issuecomment-1075221584_

**Comment by ygamboalh** [comment]
I want to be assigned to this task

**Comment by ygamboalh** [comment]
When you lose focus from any input, error must show and it doesn't

**Comment by heliomar-pena** [comment]
@ygamboalh how you go with this task? What do you think if you enter in the daily meet tomorrow and talk with us about your problem?
