### ISSUE TITLE
bug in the color of the fields

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/search-by-time-github#19]
### Explanation
you need the fields to be blank, you want the change to be made and the fields not to be red, so that the user doesn't get the impression that they are in error, this error appears in the 2 pages.

### Screenshots

Original:
![image](https://user-images.githubusercontent.com/103531307/165645528-39c0f2c0-ea26-4fe6-a606-1776f64281c0.png)
Our: 
![image](https://user-images.githubusercontent.com/103531307/165645832-772ea2df-4423-4c2a-8970-b84d5394e925.png)

Original: 
![image](https://user-images.githubusercontent.com/103531307/165833098-431516bd-a683-4a52-98ad-1b7c8ebc50e6.png)
Our: 
![image](https://user-images.githubusercontent.com/103531307/165833160-2199adf6-dd21-446d-beac-5b6d30679498.png)

### Checklist

This issue can be closed when the following tasks are complete:

- [x] on page 1 there is no red color in the fields.
- [x] on page 2 there is no red color in the fields.

### References
Original: https://www.figma.com/proto/9hPU5c4waRbBOd8msfEnKa/Search_by_time_github?node-id=2%3A8&scaling=scale-down-width&page-id=0%3A1

Our: https://azordev.github.io/search-by-time-github/

**Comment by angelik0828** [comment]
@e-azocar This change is not on the main page follows the fields of a color that does not correspond.
