### ISSUE TITLE
Add New Visual Elements To The Proyects

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/search-by-time-github#2]
### Explanation:
The project had several changes in the new design, where new visual elements are added such as the Azordev logo, the Github logo, a new background and a ´select´ to select the language.

This Pull Request includes all the visual elements but it does not include what is the form inside the box that is centered on the page. This form goes in another Pull Request.

### Screenshots
Now:
![image](https://user-images.githubusercontent.com/66505715/155402190-40cc3dc4-7553-4e20-85ee-5d40128f83e8.png)

Before:
![image](https://user-images.githubusercontent.com/66505715/155402215-1070bd73-72cf-41f4-9fc3-5195fffd81b3.png)

### Checklist
 This issue can be closed when the following tasks are completed:
 
 - [x]  Now the page has the Azordev logo at the top left on Desktop and at the bottom left on mobile,
 - [x] Now the page has a **select** at the top right to select the language. When you click on it you have two options: English & Spanish.
 - [x] Now the page has the background shown in the image.

### References:
- https://www.figma.com/file/Pw5EfnvCLnXox2mFS40kdW/Azordev?node-id=0%3A1

**Comment by arodriguezl9302** [comment]
I want to be assigned to this task
