### ISSUE TITLE
Implementation Of The Design Of Forms

### ISSUE THREAD

**Issue by angelik0828** [Azordev/search-by-time-github#3]
### Explanation:
This should take into account a centered container just below the Git hub logo, this will have two text fields and one that allows you to choose issues or Pull Request, add right-aligned button under text fields.

### Screenshots
![image](https://user-images.githubusercontent.com/4030477/155402326-01d6ca2b-030c-45a1-ae33-0e64889825c9.png)

### Checklist
  
 - [ ] 2 px border container, color `#C4C4C4`, will have a max width of 526X388px in size.
 - [ ] Two text fields will have a 1px border color `#C4C4C4` font color `#000000` font type : Montserrat light.
 - [ ] Text field that will have a select, to choose the option Issue and Pull requests.
 - [ ] Color button `#001E66`
 
### References
https://www.figma.com/file/Pw5EfnvCLnXox2mFS40kdW/Azordev?node-id=0%3A1

**Comment by ygamboalh** [comment]
I want to be assigned to this task

**Comment by carlosluis911207** [comment]
I want to be assigned to this task
