### ISSUE TITLE
Bug In The Text Of The Selected Language  /  Error En El texto Del Idioma Seleccionado

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/search-by-time-github#32]
### Explanation:
The text Select language should be closer to the left side of the box, the font is not correct, we want the modification to be done and the text to be closer to the left side of the box, so that the user can see the text with a better presentation, this error occurs in all three language options. (it is presented in all fields and sources)

**Actual result:** The text is not centered. The font is not correct.

**Expected result:** That the text is centered. That the font is correct.

*Screen size:*  Full screen.

### Screenshots:
Original: 
![image](https://user-images.githubusercontent.com/103531307/169593296-461f5329-e3a4-45c8-9177-c1fad134a128.png)

Our: 
![image](https://user-images.githubusercontent.com/103531307/169593320-195d2e38-240d-4449-8aa6-76e023dc7790.png)
![image](https://user-images.githubusercontent.com/103531307/169593336-efcd3a93-de46-477f-84e8-c68a9a99fddf.png)

### Checklist:
This issue can be closed when the following tasks are completed:
 
 - [ ] When the texts look more centered.
 - [ ] When the font is correct.

### References:

Original: https://www.figma.com/proto/9hPU5c4waRbBOd8msfEnKa/Search_by_time_github?node-id=2%3A8&scaling=scale-down&page-id=0%3A1
Our: https://github.com/Azordev/search-by-time-github

Spanish Version:

### Explicación:
El texto Seleccionar idioma debe estar más cerca del lado izquierdo del cuadro, la fuente no es correcta, queremos que se realice la modificación y que el texto esté más cerca del lado izquierdo del cuadro, para que el usuario pueda ver el texto. Con una mejor presentación, este error ocurre en las tres opciones de idioma. (presentado en todos los campos y fuentes)

**Resultado real:** El texto no está centrado, la fuente no es correcta.

**Resultado esperado:** Que el texto esté centrado. Que la fuente sea correcta.

*Tamaño de pantalla:* Pantalla completa.

### Capturas de pantalla:
Original:
![imagen](https://user-images.githubusercontent.com/103531307/169593296-461f5329-e3a4-45c8-9177-c1fad134a128.png)

Nuestro:
![imagen](https://user-images.githubusercontent.com/103531307/169593320-195d2e38-240d-4449-8aa6-76e023dc7790.png)
![imagen](https://user-images.githubusercontent.com/103531307/169593336-efcd3a93-de46-477f-84e8-c68a9a99fddf.png)

### Lista de Verificación:
Este problema se puede cerrar cuando se completen las siguientes tareas:
 
 - [ ] Cuando los textos se vean más centrados.
 - [ ] Cuando la fuente  sea correcta.

### Referencias:
Original: https://www.figma.com/proto/9hPU5c4waRbBOd8msfEnKa/Search_by_time_github?node-id=2%3A8&scaling=scale-down&page-id=0%3A1
Nuestro: https://github.com/Azordev/search-by-time-github

**Comment by Israel-Laguan** [comment]
I propose EE-2

**Comment by angelik0828** [comment]
@mdrianislam0or1  this task has not yet been validated by QA and is missing some things, please note that you can perform the tasks once you have the relevant tags.
