### ISSUE TITLE
Bug In Box Space And Bottom  /  Error En El Espacio Del Cuadro Y La parte inferior.

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/search-by-time-github#33]
# Explanation:

More space is needed between the box and the footer. It is desired that the modification be made and that the required space exists, so that when looking at the page it looks well presented. It is recommended to correct the scroll.

**Current result:** There is not much space between the box and the bottom of the page, There is scroll on the page.

**Expected result:** That there is more space between the box and the bottom of the page. There should be no scrolling on the page.

*Screen size:* Full screen.

## Screenshots:

Original: 
![image](https://user-images.githubusercontent.com/103531307/169598944-4728204a-0f78-42f6-8ecb-d2229971bd36.png)

Our: 
![image](https://user-images.githubusercontent.com/103531307/169598967-36aed751-add0-46a0-a99a-966ab8f5724e.png)

## Checklist:
This issue can be closed when the following tasks are completed:
 
 - [ ] When the space between the box and the bottom of the page is as expected here.
 - [ ] When the scroll has been corrected.

## References:
 
Original: https://www.figma.com/proto/9hPU5c4waRbBOd8msfEnKa/Search_by_time_github?node-id=2%3A8&scaling=scale-down&page-id=0%3A1
Our: https://github.com/Azordev/search-by-time-github

----

# Spanish Version:

## Explicación:
Se necesita más espacio entre el cuadro y el pie de página. Se desea que se realice la modificación y que exista el espacio requerido, para que al mirar la página se vea bien presentada. Se recomienda corregir el scroll o desplazamiento.

**Resultado actual:** No hay mucho espacio entre el cuadro y la parte inferior de la página. Hay desplazamiento en la página.

**Resultado esperado:** Que haya más espacio entre el cuadro y la parte inferior de la página. No debería haber desplazamiento en la página.

*Tamaño de la pantalla:* Pantalla completa.

## Capturas de pantalla:
Original:
![imagen](https://user-images.githubusercontent.com/103531307/169598944-4728204a-0f78-42f6-8ecb-d2229971bd36.png)

Nuestro:
![imagen](https://user-images.githubusercontent.com/103531307/169598967-36aed751-add0-46a0-a99a-966ab8f5724e.png)

## Lista de Verificación:
Este problema se puede cerrar cuando se completen las siguientes tareas:
 
 - [ ] Cuando el espacio entre el cuadro y la parte inferior de la página es el esperado aquí.
 - [ ] Cuando se haya corregido el scroll o desplazamiento.

## Referencias:

Original: https://www.figma.com/proto/9hPU5c4waRbBOd8msfEnKa/Search_by_time_github?node-id=2%3A8&scaling=scale-down&page-id=0%3A1
Nuestro: https://github.com/Azordev/search-by-time-github

**Comment by Israel-Laguan** [comment]
Please define "expected" here, like how to know it is good?

**Comment by angelik0828** [comment]
@roberto-97c  please place a measure or a suggestion in the desired sizes, mention other details that are helpful for the programmer.

**Comment by roberto-97c** [comment]
I propose (380x 280) of size.

**Comment by Israel-Laguan** [comment]
> Please define "expected" here, like how to know it is good?

Please confirm @angelik0828 if you understand what this "expected" means?

**Comment by angelik0828** [comment]
![image](https://user-images.githubusercontent.com/4030477/174310232-14b58e76-2a69-450b-91d7-ba473d225da5.png)
