### ISSUE TITLE
Bottom Blue Line Is Missing  /  Falta La Línea Azul Inferior

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/search-by-time-github#34]
# Explanation:
The blue line is needed to be at the bottom of the page, we want the modification to be made by putting the blue line at the bottom of the page, so that when looking at the page it can be viewed.

**Actual result:** The blue line that goes at the bottom is missing.

**Expected result:** That there is the blue line at the bottom.

*Screen size:* Full screen.
## Screenshots:
Original: 
![image](https://user-images.githubusercontent.com/103531307/169600618-09e0978c-e1c7-41d7-975a-8cdc2ec2e626.png)

Our: 
![image](https://user-images.githubusercontent.com/103531307/169600689-4557637d-a532-4cab-891e-8b371231867f.png)

## Checklist:
This issue can be closed when the following tasks are completed:
 - [ ] When you can see the blue line at the bottom of the page.
## References:
Original: https://www.figma.com/proto/9hPU5c4waRbBOd8msfEnKa/Search_by_time_github?node-id=2%3A8&scaling=scale-down&page-id=0%3A1
Our: https://github.com/Azordev/search-by-time-github

----

# Spanish Version:

**Explicación:**
Se necesita que la línea azul esté en la parte inferior de la página. Deseamos que la modificación se realice colocando la línea azul en la parte inferior de la página, para que al mirar la página se pueda ver.

**Resultado real:** Falta la línea azul que va en la parte inferior.

**Resultado esperado:** Que haya una línea azul en la parte inferior.

*Tamaño de pantalla:* Pantalla completa.
## Capturas de pantalla:
Original:
![imagen](https://user-images.githubusercontent.com/103531307/169600618-09e0978c-e1c7-41d7-975a-8cdc2ec2e626.png)
Nuestra:
![imagen](https://user-images.githubusercontent.com/103531307/169600689-4557637d-a532-4cab-891e-8b371231867f.png)

## Lista de Verificación:
Este problema se puede cerrar cuando se completen las siguientes tareas: 
 - [ ] Cuando se pueda ver la línea azul en la parte inferior de la página.

## Referencias:
Original: https://www.figma.com/proto/9hPU5c4waRbBOd8msfEnKa/Search_by_time_github?node-id=2%3A8&scaling=scale-down&page-id=0%3A1
Nuestro: https://github.com/Azordev/search-by-time-github

**Comment by Israel-Laguan** [comment]
Maybe the blue line is from the image? @angelik0828 do you know?

**Comment by angelik0828** [comment]
initially it was not from the image but it may have been generated that way, and the image is not scaled, we could put the figure with the blue color that has #001E66

**Comment by angelik0828** [comment]
![image](https://user-images.githubusercontent.com/4030477/171663804-1463bb1d-9bcd-442e-9e45-cbdb3e7b38ed.png)


fixed!!

**Comment by hector-trompis** [comment]
This task is already passed to administration but I do not have access to be able to close it. Who collaborates with me and closes it or gives me the permissions? Thank you.
