### ISSUE TITLE
Bug In Sizes  /  Error En Los Tamaños

### ISSUE THREAD

**Issue by roberto-97c** [Azordev/search-by-time-github#36]
# Explanation:

It is necessary that the size of the AZORDEV and GitHub logo be smaller. It is desirable that the size of the logos be modified, so that it is seen with a better presentation when it is visualized.
**Actual result:** The images are very large.

**Expected result:** make the images smaller.

*Screen size:* Full screen:
### Screenshots:
Our: 
![image](https://user-images.githubusercontent.com/103531307/169608744-56ee8cef-aac6-4e2c-b8fc-65c15d286254.png)
![image](https://user-images.githubusercontent.com/103531307/169608758-4a8f24ae-aae1-4110-b3b8-f9ce2889bc36.png)

### Checklist:
This issue can be closed when the following tasks are completed:
 
 - [ ] When the size of the logos is as expected.
 - [ ] Perform verification in all mobile and desktop views

### References
Original: https://www.figma.com/proto/9hPU5c4waRbBOd8msfEnKa/Search_by_time_github?node-id=2%3A89&scaling=scale-down&page-id=0%3A1
Our: https://github.com/Azordev/search-by-time-github

Spanish Version:

# Explicación:

Es necesario que el tamaño del logo de AZORDEV y GitHub sea menor. Es deseable que se modifique el tamaño de los logos, para que se vea con una mejor presentación al ser visto.
## Resultado real: 
Las imágenes son muy grandes.

## Resultado esperado:
 Hacer las imágenes más pequeñas.

## Tamaño de pantalla:
Pantalla completa:

## Capturas de pantalla:
Nuestra:
![imagen](https://user-images.githubusercontent.com/103531307/169608744-56ee8cef-aac6-4e2c-b8fc-65c15d286254.png)
![imagen](https://user-images.githubusercontent.com/103531307/169608758-4a8f24ae-aae1-4110-b3b8-f9ce2889bc36.png)

## Lista de Verificación:
Este problema se puede cerrar cuando se completen las siguientes tareas:
 
 - [ ] Cuando el tamaño de los logos sea el esperado.
 - [ ] Verificar en todas las vistas móviles y de escritorio

## Referencias:
Original: https://www.figma.com/proto/9hPU5c4waRbBOd8msfEnKa/Search_by_time_github?node-id=2%3A89&scaling=scale-down&page-id=0%3A1
Nuestro: https://github.com/Azordev/search-by-time-github

**Comment by angelik0828** [comment]
@roberto-97c put approximate size for this view please.

**Comment by roberto-97c** [comment]
I suggest GitHub Width 100 px,  Heigth 100 px
AZORDEV Width 120 px,  Heigth 80 px

**Comment by mdrianislam0or1** [comment]
@e-azocar  This issue should be closed the height and width was changed.

**Comment by angelik0828** [comment]
![image](https://user-images.githubusercontent.com/4030477/174311349-04cb1c05-0a3d-4ba5-b86c-7534307a997e.png)

**Comment by hector-trompis** [comment]
This task is already passed to administration but I do not have access to be able to close it. Who collaborates with me and closes it or gives me the permissions? Thank you.
