### ISSUE TITLE
Create a New User Flow To Improve The User Experience

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/search-by-time-github#4]
### Explanation:
To improve the user experience, we thought of dividing the flow into 2 parts:

Part 1. The user has the options to enter what they want to see, for example: Issues or pull request?, User or organization, Repository name
Part 2. The user has the options to select the date.

This flow is with the intention that the user has to select only once the data that points to where he wants to search, and can change the times that the date requires without having to see the previous data. If you want to change that data, there will be a button that takes you to that view again.

### Screenshots
![image](https://user-images.githubusercontent.com/66505715/155405238-3c31d8cd-a37b-4ed2-9163-d93736560243.png)

![image](https://user-images.githubusercontent.com/66505715/155405287-01d83b4d-a3a8-418e-b441-c95b1cc2a447.png)

### Checklist
 This issue can be closed when the following tasks are completed:
 
 - [ ]  The first thing the user will see will be the part of the form where they can select only the address data:
 - [ ] Issues
     - [ ] User / Organization.
     - [ ] Repository name.
     - [ ] Next button.
 - [ ] The next thing the user will see when pressing the "Next" button is the part of the filters:
     - [ ] Select with the options: After of, Before of, Equals to.
     - [ ] An input type "Date" that allows you to select the date from which you want to start searching.

### Related Issues

- #6 

### References
 https://www.figma.com/file/Pw5EfnvCLnXox2mFS40kdW/Azordev?node-id=0%3A1

**Comment by carlosluis911207** [comment]
I want to be assigned to this task
