### ISSUE TITLE
Add Validation To Form Fields

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/search-by-time-github#5]
### Explanation:
Currently there is a `validateForm` function, which is in charge of validating that all the fields are filled, and once they are filled it allows you to copy the github link or click to be redirected to github with your search parameters.

This function requires validation, since the flow we created in issue #4 splits the form into 2 parts, while this function treats the form as one part.

So we need to split this function so that it treats the two parts separately. We must also add validations for the form inputs, show the error and block the buttons if the data is not correct.

### Screenshots
image 1:
![image](https://user-images.githubusercontent.com/66505715/155407298-00a2f4d8-e72a-4a5a-8723-dc0d572632b5.png)

image 2:
![image](https://user-images.githubusercontent.com/66505715/155407910-c57dd2b5-95a3-47d9-9af2-3b7c9c8a90ea.png)

### Checklist
 This issue can be closed when the following tasks are completed:
 
 - [ ] Add validations to the first flow (check image 1):
     - [ ] The field: "User / Organization" must not be empty.
     - [ ]  The field: "Repository Name" must not be empty.    
     - [ ]  If validations fail, the error message is displayed and the "Next" button is disabled
 - [ ] Add validations to the second flow (check image 2):
     - [ ] The field to select the date cannot be empty.
     - [ ] If the validations fail, the error message below the input is displayed and the "Go" and "Copy" buttons are disabled.
 
### References
- https://www.figma.com/file/Pw5EfnvCLnXox2mFS40kdW/Azordev?node-id=0%3A1
 
#### Related issues
- #4

**Comment by ygamboalh** [comment]
I want to be assigned to this task

**Comment by heliomar-pena** [comment]
You're already assigned. Thanks for the help!

**Comment by carlosluis911207** [comment]
I want to be assigned to this task
