### ISSUE TITLE
Add Logic For Button In The Form To Return To Select The Repository 

### ISSUE THREAD

**Issue by heliomar-pena** [Azordev/search-by-time-github#6]
### Explanation:

Now that the flow is divided into 2 parts, one to select the repository and one to select the date we want to go to, we need a button with which we can change the selected repository again. This theme is for adding that button and its logic.

### Screenshots
![image](https://user-images.githubusercontent.com/66505715/155409038-e92ed3f8-fcca-449f-8dc7-38376f85ce96.png)

### Checklist
 This issue can be closed when the following tasks are completed:
 
 - [ ] Now that the flow is divided into 2 parts, one to select the repository and another to select the date we want to go to, we need a button with which we can return to change the selected repository. This issue is to add that button and its logic.
 - [ ] Pressing this button it returns you to part 1 of the flow.
 - [ ] There is no error in returning to part 1, changing things and going back to the next.
 
### References
 - https://www.figma.com/file/Pw5EfnvCLnXox2mFS40kdW/Azordev?node-id=0%3A1

#### Related issues
 - #4

**Comment by arodriguezl9302** [comment]
I want to be assigned to this task

**Comment by carlosluis911207** [comment]
I want to be assigned to this task
